# (c) 2009 Dave Peck, All Rights Reserved. (http://davepeck.org/)

# This file is part of Dave Peck's Go.

# Dave Peck's Go is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Dave Peck's Go is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with Dave Peck's Go.  If not, see <http://www.gnu.org/licenses/>.


application: davepeck-go
version: 5-des-history-cache
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: static/img
  
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /apple-touch-icon.png
  static_files: static/img/apple-touch-icon.png
  upload: static/img/apple-touch-icon.png

- url: /cron/.*
  script: go.py
  login: admin

- url: /.*
  script: go.py

