# (c) 2009 Dave Peck, All Rights Reserved. (http://davepeck.org/)

# This file is part of Dave Peck's Go.

# Dave Peck's Go is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Dave Peck's Go is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with Dave Peck's Go.  If not, see <http://www.gnu.org/licenses/>.

# application: davepeck-go-hrd -- no longer needed in modern gcloud cli land?
# version: 10-python27
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
  - warmup

handlers:
  - url: /img
    static_dir: static/img
    secure: always

  - url: /css
    static_dir: static/css
    secure: always

  - url: /js
    static_dir: static/js
    secure: always

  - url: /favicon.ico
    static_files: static/img/favicon.ico
    upload: static/img/favicon.ico
    secure: always

  - url: /apple-touch-icon.png
    static_files: static/img/apple-touch-icon.png
    upload: static/img/apple-touch-icon.png
    secure: always

  - url: /cron/.*
    script: go.application
    login: admin
    secure: always

  - url: /export/.*
    script: go.application
    login: admin
    secure: always

  - url: /_ah/warmup
    script: go.application
    login: admin
    secure: always

  - url: /.*
    script: go.application
    secure: always

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
