# Generated by Django 6.0.4 on 2026-04-21 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('date_last_moved', models.DateTimeField()),
                ('current_state', models.JSONField()),
                ('history', models.JSONField(default=list)),
                ('chat_history', models.JSONField(default=list)),
                ('black_cookie', models.CharField(blank=True, max_length=64, null=True)),
                ('white_cookie', models.CharField(blank=True, max_length=64, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('has_scoring_data', models.BooleanField(default=False)),
                ('reminder_send_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_finished', False)), fields=['reminder_send_time'], name='game_reminder_idx')],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cookie', models.CharField(db_index=True, max_length=64, unique=True)),
                ('color', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wants_email', models.BooleanField(default=True)),
                ('contact_type', models.CharField(default='email', max_length=16)),
                ('show_grid', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
            ],
        ),
    ]
